package br.com.auster.rules.testing;

import br.com.auster.billcheckout.om.NamedHashMap

rule "Teste01"
 salience 100
 when
  not ( NamedHashMap ( name == "nbrs" ) )
 then
  NamedHashMap nbrs = new NamedHashMap("nbrs");
  insert(nbrs);
  System.out.println("R1. name: " + nbrs.getName()); 
end

rule "Test02"
 salience 50
 when
  $nbrs : NamedHashMap( name == "nbrs" ) 
 then
  System.out.println("R2. name: " + $nbrs.getName()); 
end

rule "Test03"
 salience 50
 when
  $nbrs : NamedHashMap( eval($nbrs.getName().equals("nbrs") ) )
 then
  System.out.println("R3. name: " + $nbrs.getName()); 
end
