DROP TABLE vivo_bck.bck_product_relation CASCADE CONSTRAINTS
/

CREATE TABLE vivo_bck.bck_product_relation
   (service1    VARCHAR2(40) not null,
    service2    VARCHAR2(40) not null,
    relation    VARCHAR2(2)  not null,
  CONSTRAINT bck_service_relation_pk
  PRIMARY KEY (service1, service2)
  USING INDEX)
  TABLESPACE  users
/

COMMENT ON COLUMN VIVO_BCK.BCK_PRODUCT_RELATION.RELATION IS
'M = MUST HAVE
C = CANNOT HAVE'
/

insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 1000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 10000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 100000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 15000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 150000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 1500000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 2000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 20000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 3000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 30000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 4000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 45000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 5000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 60000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 7000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('TEMPO & CIA 80000', 'PLANO TEMPO & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI100K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI10K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI11K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI120K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI12K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI13K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI14K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI1500', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI150K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI15K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI16K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI18K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI1K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI20K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI22K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI2500', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI25K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI2K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI30K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI3500', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI3K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI40K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI45K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI4K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI500', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI50K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI5K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI60K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI6K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI7K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI80K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI8K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOI9K', 'VIVO EMPTEMPOI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII100K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII10K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII11K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII120K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII12K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII13K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII14K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII1500', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII150K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII15K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII16K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII18K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII1K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII20K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII22K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII2500', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII25K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII2K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII30K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII3500', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII3K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII40K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII45K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII4K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII500', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII50K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII5K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII60K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII6K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII7K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII80K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII8K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOII9K', 'VIVO EMPTEMPOII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII100K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII10K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII11K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII120K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII12K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII13K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII14K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII1500', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII150K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII15K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII16K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII18K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII1K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII20K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII22K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII2500', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII25K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII2K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII30K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII3500', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII3K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII40K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII45K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII4K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII500', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII50K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII5K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII60K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII6K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII7K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII80K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII8K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPOIII9K', 'VIVO EMPTEMPOIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC100', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC100K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC10K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC120K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC150K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC15K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC1K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC200', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC20K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC2K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC300', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC30K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC3K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC400', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC45K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC4K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC50', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC500', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC50K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC5K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC60K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC7K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPONAC80K', 'VIVO EMPTEMPONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZERO III 100', 'VIVO EMPZEROIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZERO III 300', 'VIVO EMPZEROIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZERO III 500', 'VIVO EMPZEROIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZEROIII500', 'VIVO EMPZEROIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZERONAC PK', 'VIVO EMPZERONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZERONAC100PK', 'VIVO EMPZERONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZERONAC300PK', 'VIVO EMPZERONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPZERONAC500PK', 'VIVO EMPZERONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO 100', 'VIVO EMP ZERO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO 200', 'VIVO EMP ZERO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO 300', 'VIVO EMP ZERO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO 500', 'VIVO EMP ZERO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO I 100', 'VIVO EMP ZEROI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO I 300', 'VIVO EMP ZEROI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO I 500', 'VIVO EMP ZEROI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO II 100', 'VIVO EMP ZEROII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO II 300', 'VIVO EMP ZEROII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP ZERO II 500', 'VIVO EMP ZEROII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEI200', 'VIVO EMPEQUIPEI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEI400', 'VIVO EMPEQUIPEI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEI600', 'VIVO EMPEQUIPEI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEI800', 'VIVO EMPEQUIPEI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPEI1000', 'VIVO EMPEQUIPEI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEII200', 'VIVO EMPEQUIPEII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEII400', 'VIVO EMPEQUIPEII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEII600', 'VIVO EMPEQUIPEII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEII800', 'VIVO EMPEQUIPEII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPEII1000', 'VIVO EMPEQUIPEII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEIII200', 'VIVO EMPEQUIPEIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEIII400', 'VIVO EMPEQUIPEIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEIII600', 'VIVO EMPEQUIPEIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPEIII800', 'VIVO EMPEQUIPEIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPEIII1000', 'VIVO EMPEQUIPEIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPENAC200', 'VIVO EMPEQUIPENAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPENAC400', 'VIVO EMPEQUIPENAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPENAC600', 'VIVO EMPEQUIPENAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPEQUIPENAC800', 'VIVO EMPEQUIPENAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPENAC1000', 'VIVO EMPEQUIPENAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP TEMPO 12000', 'VIVO EMP TEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP TEMPO 14000', 'VIVO EMP TEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP TEMPO 9000', 'VIVO EMP TEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 100', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 1000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 10000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 100000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 11000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 12000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 120000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 13000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 14000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 150', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 1500', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 15000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 150000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 16000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 18000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 2000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 20000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 22000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 2500', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 25000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 3000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 30000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 4000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 45000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 50', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 500', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 5000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 50000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 6000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 60000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 7000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 8000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 80000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO 9000', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO200', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO300', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO3500', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMPTEMPO400', 'VIVO EMPTEMPO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 1400 DEP', 'VIVO MAIS 1400 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 1400 DEPRJ', 'VIVO MAIS 1400 TITRJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 180 DEP', 'VIVO MAIS 180 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 180 DEP RJ', 'VIVO MAIS 180 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 350 DEP', 'VIVO MAIS 350 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 350 DEP RJ', 'VIVO MAIS 350 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 650 DEP', 'VIVO MAIS 650 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 650 DEP RJ', 'VIVO MAIS 650 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 900 DEP', 'VIVO MAIS 900 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO MAIS 900 DEP RJ', 'VIVO MAIS 900 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 120 MIN DEP', 'VIVO POS 120 MIN TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 180 MIN DEP', 'VIVO POS 180 MIN', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 180 MIN DEP', 'VIVO POS 180 MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 240 MIN DEP', 'VIVO POS 240 MIN', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 240 MIN DEP', 'VIVO POS 240 MIN TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 360 MIN DEP', 'VIVO POS 360 MIN TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 600 MIN DEP', 'VIVO POS 600 MIN TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO POS 900 MIN DEP', 'VIVO POS 900 MIN TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPE1000', 'VIVOEMPEQUIP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPE200', 'VIVOEMPEQUIP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPE400', 'VIVOEMPEQUIP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPE600', 'VIVOEMPEQUIP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPEQUIPE800', 'VIVOEMPEQUIP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP EQUIPE 1000', 'VIVO EMP EQUIPE', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP EQUIPE 200', 'VIVO EMP EQUIPE', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP EQUIPE 400', 'VIVO EMP EQUIPE', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP EQUIPE 600', 'VIVO EMP EQUIPE', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO EMP EQUIPE 800', 'VIVO EMP EQUIPE', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZERO100', 'VIVOEMPRESAZERO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZERO300', 'VIVOEMPRESAZERO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZERO500', 'VIVOEMPRESAZERO', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZEROI100', 'VIVOEMPRESAZEROI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZEROI300', 'VIVOEMPRESAZEROI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZEROI500', 'VIVOEMPRESAZEROI', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZEROII100', 'VIVOEMPRESAZEROII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZEROII300', 'VIVOEMPRESAZEROII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESAZEROII500', 'VIVOEMPRESAZEROII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESZEROIII100', 'VIVOEMPRESAZEROIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESZEROIII300', 'VIVOEMPRESAZEROIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESZEROIII500', 'VIVOEMPRESAZEROIII', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESZERONAC100', 'VIVOEMPRESAZERONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESZERONAC300', 'VIVOEMPRESAZERONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPRESZERONAC500', 'VIVOEMPRESAZERONAC', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER1200', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER12000', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER1500', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER1800', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER2100', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER2400', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER2700', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER3000', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER3600', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER4200', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER4800', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER5400', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER600', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER6000', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER900', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPER9000', 'VIVOEMPSUPER', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT100000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT1200', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT12000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT14000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT1500', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT15000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT16000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT1800', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT18000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT20000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT2100', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT22000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT2400', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT25000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT2700', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT3000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT30000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT3600', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT40000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT4200', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT45000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT4800', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT50000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT5400', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT600', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT6000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT900', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVOEMPSUPTOT9000', 'VIVOEMPSUPERTOT', 'M');
insert into vivo_bck.bck_product_relation values ('COMP 120 MINUTOS-DEP', 'COMP 120 MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('COMP 180 MINUTOS-DEP', 'COMP 180 MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('COMP 360 MINUTOS-DEP', 'COMP 360 MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('COMP 600 MINUTOS-DEP', 'COMP 600 MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('COMP 900 MINUTOS-DEP', 'COMP 900 MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('EQUIPE & CIA 1000', 'PLANO EQUIPE & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('EQUIPE & CIA 200', 'PLANO EQUIPE & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('EQUIPE & CIA 400', 'PLANO EQUIPE & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('EQUIPE & CIA 600', 'PLANO EQUIPE & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('EQUIPE & CIA 800', 'PLANO EQUIPE & CIA', 'M');
insert into vivo_bck.bck_product_relation values ('PAC540MINRD PK', 'PL VIVO 60 MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('PAC 30 MIN PL15', 'PLVIVO15MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('PAC 40 MIN PL 15 PK', 'PLVIVO15MINUTOS', 'M');
insert into vivo_bck.bck_product_relation values ('ATRACAO 500 MIN', 'ATRACAOIRRESISTIVEL', 'M');
insert into vivo_bck.bck_product_relation values ('DESC ATRACAO', 'ATRACAOIRRESISTIVEL', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 1400', 'VIVO MAIS 1400 DEP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 1400', 'VIVO MAIS 1400 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 1400', 'VIVO MAIS 1400 DEP RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 1400', 'VIVO MAIS 1400 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 180', 'VIVO MAIS 180 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 180', 'VIVO MAIS 180 DEP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 180', 'VIVO MAIS 180 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 180', 'VIVO MAIS 180 DEP RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 350', 'VIVO MAIS 350 DEP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 350', 'VIVO MAIS 350 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 350', 'VIVO MAIS 350 DEP RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 350', 'VIVO MAIS 350 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 50', 'VIVO MAIS 50 DEP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 650', 'VIVO MAIS 650 DEP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 650', 'VIVO MAIS 650 DEP RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 650', 'VIVO MAIS 650 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 650', 'VIVO MAIS 650 TIT RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 90', 'VIVO MAIS 90 DEP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 90', 'VIVO MAIS 90 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 900', 'VIVO MAIS 900 DEP', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 900', 'VIVO MAIS 900 DEP RJ', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 900', 'VIVO MAIS 900 TIT', 'M');
insert into vivo_bck.bck_product_relation values ('VIVO SEMPLOC 900', 'VIVO MAIS 900 TIT RJ', 'M');
commit;

