#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  600D - Serviço Prestado por Terceiros
#
rule "600D 3rd PARTY UNIQUE" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "600D" )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_3RD_PARTY);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();                
        $usage.setCallAsLocal();     
        $usage.setDetailCFOP("1260");          
end
