#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  580D - Chamadas Internacionais em Roaming Nacional
#
rule "580D INTR U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "580D" )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_INTR);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsRoaming();   
        $usage.setCallAsInternational();         
        $usage.setDetailCFOP("1180");     
end
