#package br.com.auster.rules.vivo;

import br.com.auster.common.rules.GlobalForLog;
import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;
global br.com.auster.billcheckout.param.SimpleObjectComparation adBagReference;
global br.com.auster.billcheckout.param.SimpleObjectComparation adBagReferenceAC;

#
#  560D - Chamadas LOCAIS Recebidas em Roaming
#
rule "560D DSL1 U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "560D", 
			caption == "DESLOCAMENTO1"
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_DSL1);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsRoaming();
        $usage.setCallAsLocal(); 
        $usage.setDetailCFOP("1190");               
end

rule "560D ADx U - Qualification" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
				tag == "560D",
				caption == "ADICIONAL",				
				$ori : originState ,
		        $dst : destinationState
		)
    then
		String accState = $usage.getSection().getParentSection().getParentSection().getSubscriptionState();
		if ($dst.equals("")) {
			$usage.setCallClass(ChecklistClasses.CALL_CLASS_AD3);
		} else if (adBagReference.isValid(accState,$dst)) {
			$usage.setCallClass(ChecklistClasses.CALL_CLASS_AD1);
		} else {
			$usage.setCallClass(ChecklistClasses.CALL_CLASS_AD2);
		}
		

		#Sets the sub types		
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());       
        $usage.setCallAsRoaming();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1190");
	
		         
end
