#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  590D - Serviço de Valor Agregado
#
rule "590D VAS U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "590D" )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VAS);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());     
        $usage.setCallAsHome();                
        $usage.setCallAsLocal();   
 		$usage.setDetailCFOP("1210");
end
