#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  660D - Serviço de Dados - Jogos e Aplicações
#
rule "660D 1xRTT U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "660D" )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_1xRTT);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_GAMES);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setDetailCFOP("1230");       
end
