#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  595D - Serviço de Valor Agregado
#
rule "595D VAS U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "595D" )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VAS);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_0500);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());
        $usage.setCallAsHome();                
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1210"); 
end