#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  550D - Chamadas Internacionais
#
rule "550D INT U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "550D" 
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_INT);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());     
        $usage.setCallAsHome();
        $usage.setCallAsInternational();   
        $usage.setDetailCFOP("1150");                
end
