#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;
#
#  675D - Serviço de Dados - VIVO ZAP
#
rule "675D 1xRTT U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "675D" )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_1xRTT);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_ZAP);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setDetailCFOP("1230");      
end
