#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  670D - Serviço de Dados - VIVO Play
#
rule "670D PLAY DOWNLOAD"
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( tag == "670D" ,
        					  caption == "DOWNLOAD"
                              )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_PLAY);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_DOWNLOAD);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setDetailCFOP("1230");      
end

rule "670D PLAY STREAMING"
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
        		tag == "670D",
				caption == "STREAMING SOB DEMAND"
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_PLAY);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_STREAMING);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());
        $usage.setDetailCFOP("1230");        
end

rule "670D PLAY U"
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
        	tag == "670D",
        	eval ( !"STREAMING SOB DEMAND".equalsIgnoreCase(caption) && !"DOWNLOAD".equalsIgnoreCase(caption) )  
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_PLAY);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);          
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setDetailCFOP("1230");       
end
