import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;
import br.com.auster.common.rules.GlobalForLog;

global java.util.List results;

#
#  535D - Chamadas de Longa Distância dentro do Estado
#

rule "535D VC2 MM" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail(  tag == "535D",
        						eval(calledNumber.length() > 3),
        						eval("789".contains(calledNumber.substring(2,3)))            
                               )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC2H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MM);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsHome();
        $usage.setCallAsLongDistance();     
        $usage.setDetailCFOP("1130"); 
end

rule "535D VC2 MF" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail(
        						tag == "535D", 
        						eval(calledNumber.length() > 3),
                              	eval("_123456".contains(calledNumber.substring(2,3)))
                              )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC2H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MF);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLongDistance();     
        $usage.setDetailCFOP("1130");          
end

rule "535D VC2 NC" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail(
        						tag == "535D" ,
        						eval(calledNumber.length() > 3),
                                eval("_123456".contains(calledNumber.substring(2,3)))
                               )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC2H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_NC);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());    
        $usage.setCallAsHome();
        $usage.setCallAsLongDistance();    
        $usage.setDetailCFOP("1130");        
end
