#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;
import br.com.auster.common.rules.GlobalForLog;

global java.util.List results;
global br.com.auster.billcheckout.param.SimpleObjectComparation adBagReference;
#global br.com.auster.billcheckout.param.SimpleObjectComparation adBagReferenceAC;

#
#  570D - Chamadas LONGA DISTANCIA Originadas em Roaming
#

/*
The rule below handles LOCAL Calls made while roaming thru LD 
*/

rule "570D Local" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
				tag == "570D", 
                caption == "LOCAL" 
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1R);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());
        $usage.setCallAsRoaming();   
        $usage.setCallAsLocal();     
        $usage.setDetailCFOP("1170");           
end

rule "570D GRATIS" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
            caption == "GRATIS" 
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_FRANQUIA);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_LD);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance(); 
        $usage.setDetailCFOP("1170");               
end

rule "570D VC2R MM" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
			caption == "INTERÁREA",
			eval(calledNumber.length() > 3),
			eval("789".contains(calledNumber.substring(2,3)))
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC2R);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MM);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance(); 
        $usage.setDetailCFOP("1170");           
end

rule "570D VC2R MF" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
			caption == "INTERÁREA",
			eval(calledNumber.length() > 3),
			eval("_123456".contains(calledNumber.substring(2,3)))
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC2R);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MF);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance(); 
        $usage.setDetailCFOP("1170");              
end

rule "570D VC2R NC" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
			caption == "INTERÁREA",
			eval(calledNumber.length() > 3),         
			eval(! "_123456789".contains(calledNumber.substring(2,3)))
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC2R);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_NC);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance(); 
        $usage.setDetailCFOP("1170");             
end

rule "570D VC3R MM" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
			caption == "INTERESTADUAL",
			eval(calledNumber.length() > 3),        
			eval("789".contains(calledNumber.substring(2,3)))			
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC3R);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MM);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());   
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance(); 
        $usage.setDetailCFOP("1170");            
end

rule "570D VC3R MF" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
			caption == "INTERESTADUAL",
			eval(calledNumber.length() > 3),
			eval("_123456".contains(calledNumber.substring(2,3)))
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC3R);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MF);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());   
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance(); 
        $usage.setDetailCFOP("1170");            
end

rule "570D VC3R NC" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
			caption == "INTERESTADUAL",
			eval(calledNumber.length() > 3),
			eval(! "_123456789".contains(calledNumber.substring(2,3)))
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC3R);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_NC);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());   
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance();  
        $usage.setDetailCFOP("1170");           
end

rule "570D ADICIONAL U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 	
			tag == "570D",
			caption == "ADICIONAL", 
            $called : calledNumber ,
        	$ori : originState ,
		    $dst : destinationState                              
		)
    then
		String accState = $usage.getSection().getParentSection().getParentSection().getSubscriptionState();
		#GlobalForLog.log("INFO", "Usage:" + $usage);				
		if ($ori.equals("") && (! $called.startsWith("*")) ) {
			$usage.setCallClass(ChecklistClasses.CALL_CLASS_AD3);
		} else if ( (null != $ori) && (null != $dst) && ($ori.equals($dst)) ) { 
			$usage.setCallClass(ChecklistClasses.CALL_CLASS_AD1);
		} else if (adBagReference.isValid(accState,$ori)) {
			$usage.setCallClass(ChecklistClasses.CALL_CLASS_AD1);
		} else {
			$usage.setCallClass(ChecklistClasses.CALL_CLASS_AD2);			
		}
		
		#Sets the sub types		
		if ( $called.startsWith("*") ) { 
	        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_VC1SPV);		
		} else {
	        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        }
        
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());   
        $usage.setCallAsRoaming();   
        $usage.setCallAsLongDistance();  
        $usage.setDetailCFOP("1170");          
end

rule "570D 3RD PARTY U 1" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
			tag == "570D", 
			eval (calledNumber.startsWith("0300")) 
		)
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_3RD_PARTY);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_0300);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setDetailCFOP("1170");      
end

