#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  520D - Chamadas Locais Recebidas a Cobrar
#
rule "520D VC1C MMI De" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "520D", 
                              groupId == "De Vivo",
			                  objectType != "A"
                              )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MMI);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect();    
        $usage.setDetailCFOP("1120");          
end

rule "520D VC1C MMI Para" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "520D", 
                              groupId == "Para Vivo",
			                  objectType != "A"
                              )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MMI);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect();  
        $usage.setDetailCFOP("1120");            
end

rule "520D VC1C MF De" 
    salience 90 
    no-loop true
	when
        $usage : UsageDetail( 
                              tag == "520D", 
                              groupId == "De Fixo",
			                  objectType != "A"
                              )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MF);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());      
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect();  
        $usage.setDetailCFOP("1120");        
end

rule "520D VC1C MF Para" 
    salience 90 
    no-loop true
	when
        $usage : UsageDetail( 
                              tag == "520D", 
                              groupId == "Para Fixo",
			                  objectType != "A"
                              )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MF);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());   
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect();  
        $usage.setDetailCFOP("1120");           
end
  
rule "520D VC1C MM De" 
    salience 90 
    no-loop true
	when
        $usage : UsageDetail(  
                              tag == "520D", 
                              groupId == "De Celulares de Outr",
			                  objectType != "A"
                              )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MM);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect();   
        $usage.setDetailCFOP("1120");            
end

rule "520D VC1C MM Para" 
    salience 90 
    no-loop true
	when
        $usage : UsageDetail(  
                              tag == "520D", 
                              groupId == "Para Outros Celulare",
			                  objectType != "A"
                              )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MM);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect(); 
        $usage.setDetailCFOP("1120");             
end

rule "520D VC1C GRUPO De" 
    salience 90 
    no-loop true
	when
        $usage : UsageDetail(  
                              tag == "520D", 
                              groupId == "De Grupo",
			                  objectType != "A"
                              )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_GRUPO);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect(); 
        $usage.setDetailCFOP("1120");              
end

rule "520D VC1C GRUPO Para" 
    salience 90 
    no-loop true
	when
        $usage : UsageDetail(  
                              tag == "520D", 
                              groupId == "Para Celulares de Gr",
			                  objectType != "A"
                              )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1C);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_GRUPO);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setCallAsCollect();  
        $usage.setDetailCFOP("1120");            
end
