#package br.com.auster.rules.vivo;

import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  655D - Tons e Imagens
#
rule "655D 1xRTT U" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "655D" )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_1xRTT);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_TONS);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setDetailCFOP("1230");      
end
