import br.com.auster.om.invoice.UsageDetail;
import br.com.auster.vivo.billcheckout.util.ChecklistClasses;

global java.util.List results;

#
#  510D - Chamadas Locais
#
rule "510D Franquia 555" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "510D",
                              caption == "GRATIS", 
			                  objectType != "A",
                              calledNumber == "*555" )
    then    
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_FRANQUIA);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_555);
        $usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);
        $usage.setGuided(true);
        $usage.setGuideRule(drools.getRule().getName());       
        $usage.setCallAsHome();
        $usage.setCallAsLocal();
        $usage.setDetailCFOP("1110");
end

rule "510D Franquia Portal Voz" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "510D",
                              caption == "GRATIS", 
			                  objectType != "A",
                              calledNumber == "*2211" )
    then    
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_FRANQUIA);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_PORTALVOZ);
        $usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);
        $usage.setGuided(true);
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setDetailCFOP("1110");                   
end

rule "510D Franquia Vivo Informa" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "510D",
                              caption == "GRATIS", 
			                  objectType != "A",
                              calledNumber == "*365" )
    then    
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_FRANQUIA);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_VIVOINFORMA);
        $usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);
        $usage.setGuided(true);
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setDetailCFOP("1110");                   
end

rule "510D Portal Voz" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "510D",
                              caption != "GRATIS", 
			                  objectType != "A",
                              calledNumber == "*2211" )
    then    
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1SPV);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_PORTALVOZ);
        $usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);
        $usage.setGuided(true);
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1110");                  
end

rule "510D Vivo Informa" 
    salience 90 
    no-loop true
    when 
        $usage : UsageDetail( 
                              tag == "510D",
                              caption != "GRATIS", 
			                  objectType != "A",
                              calledNumber == "*365" )
    then    
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1SPV);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_VIVOINFORMA);
        $usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);
        $usage.setGuided(true);
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1110");                  
end

rule "510D Franquia VC1" 
    salience 90 
    no-loop true
	when
        $usage : UsageDetail( 
                              tag == "510D", 
                              caption == "GRATIS", 
			                  objectType != "A",
                              calledNumber != "*555",
                              calledNumber != "*365",
                              calledNumber != "*2211" )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_FRANQUIA);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_VC1);
        $usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);
        $usage.setGuided(true);    
        $usage.setGuideRule(drools.getRule().getName());    
        $usage.setCallAsHome();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1110");                   
end
  
rule "510D 3RD_PARTY U" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail(  
                              tag == "510D", 
                              caption != "GRATIS", 
			                  objectType != "A",
                              eval (calledNumber.startsWith("0300")) 
                              )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_3RD_PARTY);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_0300);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);
        $usage.setGuideRule(drools.getRule().getName());   
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setDetailCFOP("1110");                 
end

rule "510D VC1H MMI" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail(  
                              tag == "510D",
                              groupId == "Para Vivo",                              
                              calledNumber != "*1234", 
                              calledNumber != "*555", 
                              caption != "GRATIS",
			                  objectType != "A",
                              eval (! calledNumber.startsWith("0300"))
                               )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MMI);
        if ($usage.getTariff()==null) {
			$usage.setTariffClass(ChecklistClasses.CALL_TARIFF_UNIQUE);        
        } else {
	        $usage.setTariffClass($usage.getTariff());
        }
        $usage.setGuided(true);       
        $usage.setCallAsHome();
        $usage.setCallAsLocal(); 
        $usage.setDetailCFOP("1110");        
end

rule "510D VC1H MF" 
    salience 90
    no-loop true
    when
        $usage : UsageDetail( 
        					  tag == "510D",
        					  groupId == "Para Fixo",       					  
        					  calledNumber != "*1234",
        					  calledNumber != "*555",
        					  caption != "GRATIS",
			                  objectType != "A",
        					  eval (!calledNumber.startsWith("0300"))
        					  )
    then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MF);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true); 
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1110");                         
end

rule "510D VC1H MM" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail( 
        					  tag == "510D",
        					  groupId == "Para Celulares de Ou",        					  
        					  calledNumber != "*1234",
        					  calledNumber != "*555",
        					  caption != "GRATIS",
			                  objectType != "A",
        					  eval (! calledNumber.startsWith("0300"))
        					  )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MM);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);      
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsHome();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1110");                   
end

rule "510D VC1H Para Grupo" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail(
        				 	  tag == "510D",
        					  groupId == "Para Celulares de Gr" ,
        					  calledNumber != "*1234",
        					  calledNumber != "*555",
        					  caption != "GRATIS",
			                  objectType != "A",
        					  eval (! calledNumber.startsWith("0300"))
        					  )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_GRUPO);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);
        $usage.setGuideRule(drools.getRule().getName());
        $usage.setCallAsHome();
        $usage.setCallAsLocal();
        $usage.setDetailCFOP("1110");
end

rule "510D VC1H De Grupo" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail( 
        				 	  tag == "510D",
        				 	  groupId == "De Grupo" ,        					  
        					  calledNumber != "*1234",
        					  calledNumber != "*555",
        					  caption != "GRATIS",
			                  objectType != "A",
        					  eval (! calledNumber.startsWith("0300"))
        					  )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VC1H);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_GRUPO);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);  
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1110");                            
end

rule "510D VAS U" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail( 
        					  tag == "510D",      
							  groupId == "Serviços",
        					  calledNumber != "*1234",
        					  calledNumber != "*555",
        					  caption != "GRATIS",
			                  objectType != "A",
        					  eval (! calledNumber.startsWith("0300"))
        					 )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_VAS);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_UNIQUE);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);        
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal();  
        $usage.setDetailCFOP("1110");                  
end

rule "510D 1234 MMI" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail( 
        					  tag == "510D",
        					  calledNumber == "*1234" ,
        					  caption != "GRATIS",
			                  objectType != "A"
        					  )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_ATEND);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MMI);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);   
        $usage.setGuideRule(drools.getRule().getName()); 
        $usage.setCallAsHome();
        $usage.setCallAsLocal();    
        $usage.setDetailCFOP("1110");                   
end

rule "510D 555 MMI" 
    salience 90
    no-loop true
	when
        $usage : UsageDetail( 
        					  tag == "510D",
        					  calledNumber == "*555" ,
        					  caption != "GRATIS",
			                  objectType != "A"
        					  )
	then
        $usage.setCallClass(ChecklistClasses.CALL_CLASS_ATEND);
        $usage.setCallSubclass(ChecklistClasses.CALL_SUBCLASS_MMI);
        $usage.setTariffClass($usage.getTariff());
        $usage.setGuided(true);       
        $usage.setGuideRule(drools.getRule().getName());  
        $usage.setCallAsHome();
        $usage.setCallAsLocal();   
        $usage.setDetailCFOP("1110");                 
end
