
DROP TABLE BCK_PARM_THRESHOLD_CALLS;
DROP TABLE BCK_PARM_DUE_DATES;

DROP TABLE prc_service_price;
DROP TABLE prc_tax_rate;
DROP TABLE prc_tax_category;
DROP TABLE prc_service_free_units;
DROP TABLE prc_service;

DROP TABLE ref_import_history;

DROP TABLE om_unit_convertion;

DROP TABLE bck_account_summary;
DROP TABLE bck_checked_services;
DROP TABLE bck_scenarios;



DROP VIEW BCK_CYCLE_DM_VIEW;

DROP TABLE BCK_CONSEQUENCE_ATTR;
DROP TABLE BCK_CONSEQUENCE;

DROP TABLE BCK_ACCOUNT_DM;
DROP TABLE BCK_CARRIER_DM;
DROP TABLE BCK_CYCLE_DM;
DROP TABLE BCK_GEO_DM;
DROP TABLE BCK_TIME_DM;
DROP TABLE BCK_RULE;
DROP TABLE BCK_RULE_TYPE;

DROP SEQUENCE BCK_CONSEQUENCE_UID;
DROP SEQUENCE BCK_DIMENSIONS_UID;
DROP SEQUENCE BCK_PARAMETERS;

DROP TABLE BCK_CONTRACT_DM;
DROP TABLE BCK_RATEPLAN_DM;


