CREATE TABLE BILLCHKOW.BCK_PROCESS_CHECKPOINT (
    TRANSACTION_ID             VARCHAR2(19)        NOT NULL,
    REQUEST_KEY                VARCHAR2(128)       NOT NULL,
    REQUEST_STATUS             CHAR(1)             NOT NULL
)
TABLESPACE TD_BILLCPR1
/
